name: Streamlit App Deployment

on:
  push:
    branches:
      - main  # Executa o workflow quando há um push na branch principal
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utiliza uma máquina Ubuntu para rodar o workflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Faz o checkout do código do repositório

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Define a versão do Python (você pode ajustar conforme necessário)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requisitos.txt  # Instala as dependências do arquivo requisitos.txt

      - name: Run Streamlit App
        run: |
          streamlit run main.py --client.showErrorDetails=false
